### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by JavascriptLearner815**
I'm tryna create my own Code of Conduct. It's not going to be easy though. This isn't finished yet, so it's WIP/work-in-progress/🚧 in the title.

### CODE REVIEW

**Comment by timmy61109** [comment]
I think it is actually very difficult to write my own specifications. I also have a similar one to you. Although it is in Traditional Chinese, you can use Google Translate to read it.

**Review by timmy61109 — DISMISSED** [review]
Okay.

**Comment by JavascriptLearner815** [comment]
So far the Code of Conduct is looking good. It can be expanded a lot further, however, so this could still be considered in progress.

**Review by timmy61109 — DISMISSED** [review]

**Comment by timmy61109** [comment]
@JavascriptLearner815 If "WIP" appears in the pull request, it means you are still editing, right?

**Comment by JavascriptLearner815** [comment]
> @JavascriptLearner815 If "WIP" appears in the pull request, it means you are still editing, right?

Yes. When it is ready for major review, the title will be removed. That stage would also be major tweaking and fixing, as well.

**Review by timmy61109 — DISMISSED** [review]

**Comment by JavascriptLearner815** [comment]
Finally! Last course of action: Complete the Enforcement section.

@efficiency-org/communications-and-contributing-department

**Review by timmy61109 — DISMISSED** [review]

**Review by timmy61109 — DISMISSED** [review]

**Comment by JavascriptLearner815** [comment]
Also, I should have converted it into a draft! Silly me!

**Review by timmy61109 — APPROVED** [review]

**Review by timmy61109 — APPROVED** [review]

**Pull request merged**
