### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by JavascriptLearner815**

### CODE REVIEW

**Comment by JavascriptLearner815** [comment]
https://github.com/crichID/oss-enterprise/issues/3

**Comment by JavascriptLearner815** [comment]
[contributing]: CONTRIBUTING.md
[code-of-conduct]: CODE_OF_CONDUCT.md
[reporting]: CODE_OF_CONDUCT.md#Reporting

# Efficiency Code of Conduct
## Pledge 
We create this Code of Conduct in an effort to welcome contributors, make them feel safe and respected, and be friendly to them.
No matter who they are, they deserve to be treated like this.
For more information, read <https://en.wikipedia.org/wiki/Golden_Rule>.
## Expectations
You must follow this repository's [Contributing guidelines][contributing] in addition to this [Code of Conduct][code-of-conduct].
Relatiation is not allowed. Please go [here][reporting] to learn how to report them instead. In the meanwhile, you can @mention staff to get more attention to your report. 
## Acceptable Behavior
- Greeting new contributors 
- Using welcoming and inclusive language
- Communicating in a friendly manner

**Comment by timmy61109** [comment]
Does it mean that this is a feedback that can be automatically made through the link? Including reports, opinions and reactions?

**Comment by JavascriptLearner815** [comment]
The github-learning-lab bot was supposed to reply here 10 hours ago...\

**Comment by JavascriptLearner815** [comment]
I feel like it might have to do with me transferring to efficiency-org.

**Comment by JavascriptLearner815** [comment]
It turns out it was.

**Comment by JavascriptLearner815** [comment]
> Does it mean that this is a feedback that can be automatically made through the link? Including reports, opinions and reactions?

What feedback? 

New pull request where it's working: #8

**Comment by JavascriptLearner815** [comment]
This is a community kit for creating our Open Source projects.

**Comment by timmy61109** [comment]
> > Does it mean that this is a feedback that can be automatically made through the link? Including reports, opinions and reactions?
> 
> What feedback?
> 
> New pull request where it's working: #8

For automatic labeling, milestones, issues or merge requests, etc.

**Comment by timmy61109** [comment]
> This is a community kit for creating our Open Source projects.

I know, it’s just that I’m not sure about your direction. Do you provide any team with an example to quickly build a project?

**Comment by JavascriptLearner815** [comment]
The organization isn't really put together completely. It still needs quite a lot of work.

**Pull request closed without merging**
